[package]
name = "rust-life"
version = "0.1.1"
authors = ["Joey Gibson <joey@joeygibson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
easycurses = "0.12.2"
rand = "0.7.3"
